### ISSUE TITLE
TypeError: null is not an object (evaluating 't(r(d[1])).default.Direction'), stack:

### ISSUE THREAD

**Issue by dashu110** [the-nippy/react-native-slidepicker#12]
git clone 代码, 单独 react-native run-android 无问题

打包后 ,运行报错以下错误.
`react-native bundle --platform android --dev false --entry-file index.js --bundle-output ./test/index.android.bundle --assets-dest ./test`

注释掉 react-native-gesture-handler 就好了. 请问这个是什么问题

`2021-01-29 15:00:10.006 10938-11224/ E/DEBUG: com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 't(r(d[1])).default.Direction'), stack:
    <unknown>@456:132
    v@2:1473
    <unknown>@448:809
    v@2:1473
    <unknown>@447:226
    v@2:1473
    <unknown>@446:312
    v@2:1473
    <unknown>@445:230
    v@2:1473
    <unknown>@444:268
    v@2:1473
    <unknown>@443:124
    v@2:1473
    <unknown>@416:223
    v@2:1473
    <unknown>@6:77
    v@2:1473
    d@2:875
    global code@479:3
2021-01-29 15:00:10.008 10938-11224/ E/DEBUG:     at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
2021-01-29 15:00:10.009 10938-11224/ E/DEBUG:     at java.lang.reflect.Method.invoke(Native Method)
2021-01-29 15:00:10.009 10938-11224/ E/DEBUG:     at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
2021-01-29 15:00:10.010 10938-11224/ E/DEBUG:     at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
2021-01-29 15:00:10.011 10938-11224/ E/DEBUG:     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
2021-01-29 15:00:10.012 10938-11224/ E/DEBUG:     at android.os.Handler.handleCallback(Handler.java:873)
2021-01-29 15:00:10.013 10938-11224/ E/DEBUG:     at android.os.Handler.dispatchMessage(Handler.java:99)
2021-01-29 15:00:10.014 10938-11224/ E/DEBUG:     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
2021-01-29 15:00:10.015 10938-11224/ E/DEBUG:     at android.os.Looper.loop(Looper.java:193)
2021-01-29 15:00:10.016 10938-11224/ E/DEBUG:     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
2021-01-29 15:00:10.017 10938-11224/ E/DEBUG:     at java.lang.Thread.run(Thread.java:764)
2021-01-29 15:00:10.017 10938-11224/ E/DEBUG: Back traces ends.`

**Comment by the-nippy** [comment]
有安装react-native-gesture-handler吗，看起来是这个库没有安装或者没有引用到，打包配置是不是有问题

**Comment by dashu110** [comment]
我是B项目,作为插件被下载的, 
B项目已安装 react-native-gesture-handler


A项目是主项目, 加载 jsbundle 启动B项目.
A项目中没有 安装react-native-gesture-handler.

是否是需要在A项目中配置 react-native-gesture-handler

**Comment by lexguy** [comment]
你的jsbundle是来自A项目还是B项目？A项目是否是RN项目，主项目是RN项目的话那应该在A中安装react-native-gesture-handler.(另外你的项目RN版本是否大于0.60，前后版本这个库的依赖配置有区别，请参照文档)

**Comment by the-nippy** [comment]
> 我是B项目,作为插件被下载的,
> B项目已安装 react-native-gesture-handler
> 
> A项目是主项目, 加载 jsbundle 启动B项目.
> A项目中没有 安装react-native-gesture-handler.
> 
> 是否是需要在A项目中配置 react-native-gesture-handler

你的 jsbundle 是哪个项目生成的? 你的A项目是否是RN项目，是RN项目的话那应该在A项目中配置 react-native-gesture-handler。（另外RN0.60版本前后对库的依赖也有区别，请参照文档）
